/*
 * generated by Xtext 2.24.0
 */
package com.tachyon.zeta.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.tachyon.zeta.ZetaRuntimeModule;
import com.tachyon.zeta.ZetaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ZetaIdeSetup extends ZetaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ZetaRuntimeModule(), new ZetaIdeModule()));
	}
	
}
