/*
 * generated by Xtext 2.24.0
 */
package com.tachyon.zeta;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ZetaStandaloneSetup extends ZetaStandaloneSetupGenerated {

	public static void doSetup() {
		new ZetaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
