/*
 * generated by Xtext 2.24.0
 */
package com.tachyon.zeta;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ZetaRuntimeModule extends AbstractZetaRuntimeModule {
}
